[package]
name = "rustfix_usage"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfix = "0.5.1"
anyhow = "1.0.39"
log = "0.4.1"

[dev-dependencies]
proptest = "1.0.0"