#!/usr/bin/bash
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/basavesh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib /home/basavesh/research/rustStuff/splitspectre/target/debug/split_functions "$@"
