[package]
name = "chacha20"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secret_integers = { git = "https://github.com/basavesh/rust-secret-integers.git", branch = "bash-dev"}